//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SPNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SPNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Resources.SPNames", typeof(SPNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB_Pharmacy_ByCase.
        /// </summary>
        public static string DB_Pharmacy_ByCase {
            get {
                return ResourceManager.GetString("DB_Pharmacy_ByCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB_Pharmacy_CU.
        /// </summary>
        public static string DB_Pharmacy_CU {
            get {
                return ResourceManager.GetString("DB_Pharmacy_CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB_Pharmacy_GetAll.
        /// </summary>
        public static string DB_Pharmacy_GetAll {
            get {
                return ResourceManager.GetString("DB_Pharmacy_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB_Pharmacy_GetInfo.
        /// </summary>
        public static string DB_Pharmacy_GetInfo {
            get {
                return ResourceManager.GetString("DB_Pharmacy_GetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_DropDown.
        /// </summary>
        public static string Pharmacy_DropDown {
            get {
                return ResourceManager.GetString("Pharmacy_DropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_GetAllPersonel.
        /// </summary>
        public static string Pharmacy_GetAllPersonel {
            get {
                return ResourceManager.GetString("Pharmacy_GetAllPersonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_GetAllUser.
        /// </summary>
        public static string Pharmacy_GetAllUser {
            get {
                return ResourceManager.GetString("Pharmacy_GetAllUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_GetAllUserByCase.
        /// </summary>
        public static string Pharmacy_GetAllUserByCase {
            get {
                return ResourceManager.GetString("Pharmacy_GetAllUserByCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_GetParishs.
        /// </summary>
        public static string Pharmacy_GetParishs {
            get {
                return ResourceManager.GetString("Pharmacy_GetParishs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_GetPersonelInfo.
        /// </summary>
        public static string Pharmacy_GetPersonelInfo {
            get {
                return ResourceManager.GetString("Pharmacy_GetPersonelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_GetUserInfo.
        /// </summary>
        public static string Pharmacy_GetUserInfo {
            get {
                return ResourceManager.GetString("Pharmacy_GetUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_Medicine_ByCase.
        /// </summary>
        public static string Pharmacy_Medicine_ByCase {
            get {
                return ResourceManager.GetString("Pharmacy_Medicine_ByCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_Medicine_CU.
        /// </summary>
        public static string Pharmacy_Medicine_CU {
            get {
                return ResourceManager.GetString("Pharmacy_Medicine_CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_Medicine_GetAll.
        /// </summary>
        public static string Pharmacy_Medicine_GetAll {
            get {
                return ResourceManager.GetString("Pharmacy_Medicine_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_Medicine_GetInfo.
        /// </summary>
        public static string Pharmacy_Medicine_GetInfo {
            get {
                return ResourceManager.GetString("Pharmacy_Medicine_GetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_Menu.
        /// </summary>
        public static string Pharmacy_Menu_GetAll {
            get {
                return ResourceManager.GetString("Pharmacy_Menu_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_MenuShortcut.
        /// </summary>
        public static string Pharmacy_Menu_GetAllShortcut {
            get {
                return ResourceManager.GetString("Pharmacy_Menu_GetAllShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_Patient_ByCase.
        /// </summary>
        public static string Pharmacy_Patient_ByCase {
            get {
                return ResourceManager.GetString("Pharmacy_Patient_ByCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_Patient_CU.
        /// </summary>
        public static string Pharmacy_Patient_CU {
            get {
                return ResourceManager.GetString("Pharmacy_Patient_CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_Patient_GetAll.
        /// </summary>
        public static string Pharmacy_Patient_GetAll {
            get {
                return ResourceManager.GetString("Pharmacy_Patient_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_Patient_GetInfo.
        /// </summary>
        public static string Pharmacy_Patient_GetInfo {
            get {
                return ResourceManager.GetString("Pharmacy_Patient_GetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_Personnel_ByCase.
        /// </summary>
        public static string Pharmacy_Personnel_ByCase {
            get {
                return ResourceManager.GetString("Pharmacy_Personnel_ByCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_Personnel_CU.
        /// </summary>
        public static string Pharmacy_Personnel_CU {
            get {
                return ResourceManager.GetString("Pharmacy_Personnel_CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_Personnel_GetAll.
        /// </summary>
        public static string Pharmacy_Personnel_GetAll {
            get {
                return ResourceManager.GetString("Pharmacy_Personnel_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_Personnel_GetInfo.
        /// </summary>
        public static string Pharmacy_Personnel_GetInfo {
            get {
                return ResourceManager.GetString("Pharmacy_Personnel_GetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_RolesByUserId.
        /// </summary>
        public static string Pharmacy_Roles_ByUserId {
            get {
                return ResourceManager.GetString("Pharmacy_Roles_ByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_UserLogin.
        /// </summary>
        public static string Pharmacy_Security_User_Login {
            get {
                return ResourceManager.GetString("Pharmacy_Security_User_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_RefreshToken.
        /// </summary>
        public static string Pharmacy_SetRefreshToken {
            get {
                return ResourceManager.GetString("Pharmacy_SetRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_MenuPermission.
        /// </summary>
        public static string Pharmacy_User_GetMenuPermission {
            get {
                return ResourceManager.GetString("Pharmacy_User_GetMenuPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_UserMenuPermission.
        /// </summary>
        public static string Pharmacy_UserMenuPermission_CU {
            get {
                return ResourceManager.GetString("Pharmacy_UserMenuPermission_CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_Warehouse_ByCase.
        /// </summary>
        public static string Pharmacy_Warehouse_ByCase {
            get {
                return ResourceManager.GetString("Pharmacy_Warehouse_ByCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_Warehouse_CU.
        /// </summary>
        public static string Pharmacy_Warehouse_CU {
            get {
                return ResourceManager.GetString("Pharmacy_Warehouse_CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_Warehouse_GetAll.
        /// </summary>
        public static string Pharmacy_Warehouse_GetAll {
            get {
                return ResourceManager.GetString("Pharmacy_Warehouse_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy_Warehouse_GetInfo.
        /// </summary>
        public static string Pharmacy_Warehouse_GetInfo {
            get {
                return ResourceManager.GetString("Pharmacy_Warehouse_GetInfo", resourceCulture);
            }
        }
    }
}
